train:
  batch_size: 64
  shuffle: True
  num_workers: 4
  epochs: 1000
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0002

test:
  batch_size: 64
  shuffle: False
  num_workers: 4

image_index:
  - 15

embedding_ch: 64

gcn_in_ch: 3

augmentation:
  Normalize:
#    mean: [ 0.485, 0.456, 0.406 ]
#    std: [ 0.229, 0.224, 0.225 ]
    mean: [0.26179731, 0.23205107, 0.2547063 ]
    std: [0.14784886, 0.14375395, 0.13930466]